const refreshPakistanIcons = () => { if (window.lucide) window.lucide.createIcons(); };
refreshPakistanIcons();
const reducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const revealObserver = new IntersectionObserver((entries, observer) => { entries.forEach((entry) => { if (!entry.isIntersecting) return; entry.target.classList.add('visible'); observer.unobserve(entry.target); }); }, { threshold: 0.12 });
document.querySelectorAll('.reveal').forEach((element) => { if (reducedMotion) element.classList.add('visible'); else revealObserver.observe(element); });
const menuToggle = document.querySelector('.menu-toggle');
const mainNav = document.querySelector('.main-nav');
menuToggle?.addEventListener('click', () => { const open = mainNav.classList.toggle('open'); menuToggle.setAttribute('aria-expanded', String(open)); menuToggle.querySelector('.sr-only').textContent = open ? 'Close menu' : 'Open menu'; });
mainNav?.querySelectorAll('a').forEach((link) => link.addEventListener('click', () => { mainNav.classList.remove('open'); menuToggle?.setAttribute('aria-expanded', 'false'); }));
const tabs = [...document.querySelectorAll('.pk-tab')];
const panels = [...document.querySelectorAll('.pk-panel')];
const selectPanel = (index) => { const tab = tabs[index]; if (!tab) return; tabs.forEach((item, itemIndex) => { const selected = itemIndex === index; item.classList.toggle('active', selected); item.setAttribute('aria-selected', String(selected)); item.tabIndex = selected ? 0 : -1; }); panels.forEach((panel) => { panel.hidden = panel.id !== tab.getAttribute('aria-controls'); }); refreshPakistanIcons(); };
tabs.forEach((tab, index) => { tab.addEventListener('click', () => selectPanel(index)); tab.addEventListener('keydown', (event) => { if (!['ArrowDown', 'ArrowRight', 'ArrowUp', 'ArrowLeft', 'Home', 'End'].includes(event.key)) return; event.preventDefault(); const next = event.key === 'Home' ? 0 : event.key === 'End' ? tabs.length - 1 : event.key.includes('Down') || event.key.includes('Right') ? (index + 1) % tabs.length : (index - 1 + tabs.length) % tabs.length; selectPanel(next); tabs[next].focus(); }); });
selectPanel(0);
